import type { ConnectorCapability, ServiceId } from './types.js';

const NONE: Omit<ConnectorCapability, 'apiAuth' | 'integrationMode'> = {
  readMetadata: false,
  readRatings: false,
  writeRatings: false,
  importRatings: false,
  exportRatings: false,
  readWatched: false,
  writeWatched: false,
  importWatched: false,
  exportWatched: false,
  readWatchlist: false,
  writeWatchlist: false,
  importWatchlist: false,
  exportWatchlist: false,
  readReviews: false,
  writeReviews: false,
  importReviews: false,
  exportReviews: false,
  readFollowing: false,
  writeFollowing: false,
  importFollowing: false,
  readFollowers: false,
  exportFollowing: false,
  exportFollowers: false
};

export const SERVICE_CAPABILITIES: Record<ServiceId, ConnectorCapability> = {
  imdb: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    exportRatings: true,
    readWatched: true,
    exportWatched: true,
    readWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'none',
    integrationMode: 'official-export',
    notes: 'Shipped readers accept IMDb ratings, Check-ins, and watchlist exports. Check-ins become timestamp-free watched membership because their list creation time is not guaranteed to be the actual viewing time. The portable ratings CSV helper does not imply IMDb account import or a direct account writer.'
  },
  'rotten-tomatoes': {
    ...NONE,
    readMetadata: true,
    apiAuth: 'unknown',
    integrationMode: 'partner-or-request-only',
    notes: 'No connector or mapped-file workflow is enabled unless approved API or partner access is granted.'
  },
  letterboxd: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    readReviews: true,
    importReviews: true,
    exportReviews: true,
    apiAuth: 'unknown',
    integrationMode: 'official-export-import',
    notes: 'Shipped readers accept official account exports. A shipped generator creates user-controlled files for Letterboxd’s documented web importer; no direct account writer is claimed.'
  },
  tmdb: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Uses a user-authorized v4 token and account object ID for exports; v3 writes also require a converted session and numeric account ID.'
  },
  omdb: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'api-key',
    integrationMode: 'metadata-only',
    notes: 'Exact IMDb-ID metadata lookup with a caller-provided OMDb API key. No title search, poster API, account, or user-data path is shipped. OMDb content is CC BY-NC 4.0 and its terms limit use to personal, non-commercial purposes.'
  },
  'tv-time': {
    ...NONE,
    apiAuth: 'unknown',
    integrationMode: 'manual',
    notes: 'No public write API is assumed. Support user data export if available and manual workflows.'
  },
  trakt: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    readReviews: true,
    writeReviews: true,
    importReviews: true,
    exportReviews: true,
    readFollowing: true,
    writeFollowing: true,
    importFollowing: true,
    readFollowers: true,
    exportFollowing: true,
    exportFollowers: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Official Trakt API support for ratings, watched history, watchlist, current-user top-level reviews, following, and followers. Review creation requires exact Trakt IDs and cannot preserve timestamps or attached ratings. Following writes are additive, exact-username verified, and public-profile only; relationship timestamps and profile URLs cannot be written. Followers are always read-only.'
  },
  simkl: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Official Simkl API supports movies, TV, anime, sync, and scrobbling.'
  },
  metacritic: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'unknown',
    integrationMode: 'manual',
    notes: 'Treat as read-only/manual unless a compliant API or export is provided.'
  },
  justwatch: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'unknown',
    integrationMode: 'partner-or-request-only',
    notes: 'Use only approved API/partner data or manual links; do not scrape.'
  },
  reelgood: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'unknown',
    integrationMode: 'manual',
    notes: 'Manual/export workflow unless a supported API is provided.'
  },
  serializd: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    readWatched: true,
    readWatchlist: true,
    readReviews: true,
    apiAuth: 'unknown',
    integrationMode: 'manual',
    notes: 'Manual/export connector until official API support is confirmed.'
  },
  thetvdb: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'api-key',
    integrationMode: 'metadata-only',
    notes: 'V4 metadata resolver requires a caller-provided authorized project key and, for user-supported access, subscriber PIN.'
  },
  tvmaze: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'none',
    integrationMode: 'metadata-only',
    notes: 'Public TV metadata resolver; it cannot read or write a user account.'
  },
  allmovie: { ...NONE, readMetadata: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/read-only profile.' },
  criticker: { ...NONE, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile until official API is confirmed.' },
  movielens: { ...NONE, readMetadata: true, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'official-export', notes: 'Shipped reader accepts a user-owned ratings export; no MovieLens-target file generator is shipped.' },
  filmaffinity: { ...NONE, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile.' },
  flickchart: { ...NONE, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Rankings may need a custom mapping to ratings.' },
  tastedive: { ...NONE, readMetadata: true, apiAuth: 'api-key', integrationMode: 'metadata-only', notes: 'Recommendation metadata connector.' },
  tasteio: { ...NONE, readRatings: true, readWatchlist: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile.' },
  mubi: { ...NONE, readRatings: true, readWatchlist: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile.' },
  'common-sense-media': { ...NONE, readMetadata: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Metadata/reference connector only.' },
  myanimelist: {
    ...NONE,
    readMetadata: true,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Anime/manga connector; use official OAuth API.'
  },
  kitsu: {
    ...NONE,
    readMetadata: true,
    apiAuth: 'none',
    integrationMode: 'metadata-only',
    notes: 'Current official OpenAPI supports public exact-ID reads for anime, manga, and episodes only. Library entries, users, mappings, and their schemas are commented out, so ratings, watched/progress, watchlist, search, mapping, and account authentication remain unsupported.'
  },
  shikimori: {
    ...NONE,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Official OAuth user-rates API for anime. WatchBridge preserves mutually exclusive planned, watching, rewatching, completed, on-hold, and dropped states plus bounded episode progress and replay count. Rating-only writes require an existing user rate; provider timestamps cannot be preserved.'
  },
  annict: {
    ...NONE,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Official REST v1 plus documented GraphQL viewer records for exact episode play counts and work-level watching, completed, on-hold, dropped, and planned states. Writes are monotonic/additive and reject timestamps or progress. Annict ratings belong to individual episode records and are intentionally not modeled as one title rating.'
  },
  bangumi: {
    ...NONE,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'oauth2',
    integrationMode: 'official-api',
    notes: 'Official v0 OAuth API for anime collections. Watched sync preserves collection status plus exact completed episode IDs. Rating writes require an existing collection, and provider timestamps are rejected because the write contract cannot preserve them. On-hold/dropped states and book progress are not modeled.'
  },
  jellyfin: {
    ...NONE,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    apiAuth: 'session-token',
    integrationMode: 'official-api',
    notes: 'Official per-user API for numeric personal Rating and completed Played state on one explicitly configured HTTPS server. WatchBridge bounds Rating to 0-10 in 0.1 steps even though Jellyfin does not enforce that range. Favorites are not watchlists and remain unsupported.'
  },
  emby: {
    ...NONE,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    apiAuth: 'session-token',
    integrationMode: 'official-api',
    notes: 'Official per-user API for completed Played membership on movies and exact episodes from one explicitly configured HTTPS server. Aggregate series, progress, timestamps, replay counts, ratings, favorites, and watchlists are not represented.'
  },
  kodi: {
    ...NONE,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    readWatchlist: true,
    writeWatchlist: true,
    importWatchlist: true,
    exportWatchlist: true,
    apiAuth: 'basic',
    integrationMode: 'official-api',
    notes: 'Kodi Omega JSON-RPC v13.5 support for integer personal userrating, movie/exact-episode playcount, and an additive movie watchlist represented by a WatchBridge-managed tag namespaced to one explicitly scoped library/profile. Favourites are not treated as watchlists. Episode watchlist membership, resume progress, last-played timestamps, aggregate series state, and endpoint-derived identity are unsupported.'
  },
  plex: {
    ...NONE,
    readRatings: true,
    writeRatings: true,
    importRatings: true,
    exportRatings: true,
    readWatched: true,
    writeWatched: true,
    importWatched: true,
    exportWatched: true,
    apiAuth: 'session-token',
    integrationMode: 'official-api',
    notes: 'Official Plex Media Server API support for personal userRating plus completed played membership for movies and exact episodes on one explicitly selected and machine-ID-verified server. Rating keys are server-scoped. The provider-discovered scrobble endpoint sets played state without creating view history, so progress, replay counts, timestamps, aggregate show/season state, global watchlist, and rating deletion remain unsupported.'
  },
  anilist: {
    ...NONE,
    apiAuth: 'unknown',
    integrationMode: 'partner-or-request-only',
    notes: 'No connector is enabled pending explicit authorization for this sustained tracking use case.'
  },
  'douban-movie': { ...NONE, readMetadata: true, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile due API availability uncertainty.' },
  kinopoisk: { ...NONE, readMetadata: true, readRatings: true, exportRatings: true, apiAuth: 'unknown', integrationMode: 'manual', notes: 'Manual/export profile due API availability uncertainty.' }
};

export function getCapabilities(service: ServiceId): ConnectorCapability {
  return SERVICE_CAPABILITIES[service];
}
